org: shonore99
app: flight-recommender
service: flight-recommender-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.poc
    events:
      - httpApi:
          path: /
          method: get
  recommend:
    handler: recommender.getItineraries
    events:
      - httpApi:
          path: /recommend
          method: get  